version: '3.1'

services:
  frontend:
    build:  ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/usr/app/:ro
      - /usr/app/node_modules/
    ports:
      - 80:80
    links:
      - backend
    environment:
        NODE_ENV: "${ENV}"
  backend:
    build: ./backend
    command: adev runserver
    volumes:
      - ./backend:/usr/app/:ro
    secrets:
      - authkey
    depends_on:
      - db
  db:
    image: mongo:4.2.1
    environment:
      MONGO_INITDB_DATABASE: moti
    volumes:
      - ./db/volume:/data/db
      - ./db/fixtures.js:/docker-entrypoint-initdb.d/fixtures.js:ro
    ports:
      - 27017:27017

secrets:
  authkey:
    file: ./.authkey
